"""
Automated Unit Tests for EduGenie Modular Architecture
"""

import unittest
import json
from backend.parsers import clean_json_output, generate_export_document, extract_delimited_section
from backend.gemini_client import handle_gemini_error, resolve_api_key


class TestEduGenieBackend(unittest.TestCase):

    def test_clean_json_output_with_markdown_fences(self):
        """Test that JSON markdown code blocks are properly stripped."""
        raw_llm_output = """```json
[
  {
    "id": 1,
    "question": "What is 2+2?",
    "options": ["3", "4", "5", "6"],
    "correct_answer": "4",
    "explanation": "Basic addition."
  }
]
```"""
        cleaned = clean_json_output(raw_llm_output)
        parsed = json.loads(cleaned)
        self.assertIsInstance(parsed, list)
        self.assertEqual(len(parsed), 1)
        self.assertEqual(parsed[0]["correct_answer"], "4")

    def test_clean_json_output_plain(self):
        """Test clean_json_output handles raw JSON without backticks."""
        raw_json = '[{"front": "Term", "back": "Definition"}]'
        cleaned = clean_json_output(raw_json)
        parsed = json.loads(cleaned)
        self.assertEqual(parsed[0]["front"], "Term")

    def test_handle_gemini_error_rate_limit(self):
        """Test that 429 quota exceptions map to user-friendly messages."""
        mock_exception = Exception("429 ResourceExhausted: Quota exceeded for model gemini-1.5-pro")
        message = handle_gemini_error(mock_exception)
        self.assertIn("Rate Limit Exceeded", message)
        self.assertIn("gemini-1.5-flash", message)

    def test_handle_gemini_error_auth_failure(self):
        """Test that 403 API key exceptions map to actionable advice."""
        mock_exception = Exception("403 API_KEY_INVALID: API key not valid.")
        message = handle_gemini_error(mock_exception)
        self.assertIn("Invalid API Key", message)
        self.assertIn("Google AI Studio", message)

    def test_extract_delimited_section(self):
        """Test structured delimiter extraction."""
        sample_doc = """[SECTION: Core Intuition]
This is the core concept.
[SECTION: Deep Breakdown]
Here is the mechanism."""
        intuition = extract_delimited_section(sample_doc, "Core Intuition")
        breakdown = extract_delimited_section(sample_doc, "Deep Breakdown")
        self.assertEqual(intuition, "This is the core concept.")
        self.assertEqual(breakdown, "Here is the mechanism.")

    def test_generate_export_document_html(self):
        """Test HTML document generation utility."""
        title = "Calculus Revision"
        content = "Derivatives represent instantaneous rate of change."
        html_output = generate_export_document(title, content, doc_format="html")
        self.assertIn("<title>Calculus Revision - EduGenie Study Material</title>", html_output)
        self.assertIn("Derivatives represent instantaneous rate of change.", html_output)
        self.assertIn("Generated by EduGenie AI", html_output)

    def test_generate_export_document_txt(self):
        """Test plain text document export utility."""
        title = "Physics"
        content = "# Newton's Law\nF = ma"
        txt_output = generate_export_document(title, content, doc_format="txt")
        self.assertIn("=== Physics ===", txt_output)
        self.assertIn("Newton's Law", txt_output)


if __name__ == "__main__":
    unittest.main()
