"""
Parsers, file extractors, and formatting utilities for EduGenie.
"""

import io
import re
from typing import Optional
from PIL import Image
from pypdf import PdfReader


def clean_json_output(raw_text: str) -> str:
    """Cleans markdown JSON code blocks from LLM output."""
    if not raw_text:
        return ""
    raw_text = raw_text.strip()
    match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", raw_text)
    if match:
        return match.group(1).strip()
    return raw_text


def extract_text_from_pdf(file_bytes: bytes) -> str:
    """Extracts text content from uploaded PDF bytes."""
    try:
        reader = PdfReader(io.BytesIO(file_bytes))
        extracted_text = []
        for page in reader.pages:
            t = page.extract_text()
            if t:
                extracted_text.append(t)
        return "\n".join(extracted_text)
    except Exception as e:
        return f"Error extracting PDF text: {str(e)}"


def process_image(file_bytes: bytes) -> Optional[Image.Image]:
    """Processes uploaded image bytes into a PIL Image."""
    try:
        return Image.open(io.BytesIO(file_bytes))
    except Exception:
        return None


def extract_delimited_section(text: str, section_name: str) -> Optional[str]:
    """Extracts a section from structured text formatted with [SECTION: Name]."""
    if not text:
        return None
    pattern = rf"\[SECTION:\s*{section_name}\]([\s\S]*?)(?=\[SECTION:|$)"
    match = re.search(pattern, text, re.IGNORECASE)
    return match.group(1).strip() if match else None


def generate_export_document(title: str, markdown_content: str, doc_format: str = "html") -> str:
    """Generates formatted document content for export (.html, .txt, .md)."""
    if doc_format == "html":
        return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{title} - EduGenie Study Material</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            line-height: 1.6;
            color: #1e293b;
            max-width: 800px;
            margin: 40px auto;
            padding: 0 20px;
        }}
        h1, h2, h3 {{ color: #4338ca; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; }}
        pre, code {{ background: #f1f5f9; padding: 2px 6px; border-radius: 4px; font-family: monospace; }}
        .header {{ text-align: center; margin-bottom: 30px; }}
        .badge {{ background: #4f46e5; color: white; padding: 4px 10px; border-radius: 12px; font-size: 0.85em; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{title}</h1>
        <span class="badge">Generated by EduGenie AI</span>
    </div>
    <div class="content">
        {markdown_content.replace(chr(10), '<br>')}
    </div>
</body>
</html>"""
    elif doc_format == "txt":
        # Strip markdown syntax for plain text
        clean_text = re.sub(r"[#*_`]", "", markdown_content)
        return f"=== {title} ===\n\n{clean_text}"
    return markdown_content
